### ISSUE TITLE
Add Support for Delete Location History Endpoint

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-android#20]
Add support for the [Delete Location History](https://m2x.att.com/developer/documentation/v2/device#Delete-Location-History) endpoint of the Device API.

**Comment by majidabdul** [comment]
Hello @kristinpeterson, 

We started work on this issue and when we try to execute this API, getting an error as “Missing parameter from” and executed the existing deleteDataStreamValues API which is also getting the same error.
 
Please find our observations as below.

Currently in Android Volley Library, REST API call ( Delete Operation ) with JSON object body request is not working properly. We found the root cause for this issue with below URL.
http://stackoverflow.com/questions/19050706/android-volley-delete-method-why-will-send-empty-parameters

We are thinking to make below changes in hurlstack class in volley library.

`case` `Method.DELETE:`
             `connection`.`setRequestMethod("DELETE");`
             `addBodyIfExists(connection, request);` // here call addBodyIfExists method
             `break;`
 
Since the Volley lib doesn’t add the body for `DELETE` request, modified the code in `JsonRequest.java` as passing the arguments as query parameters instead of JSON objects body (current implementation was passing null for query parameters) & found that the “DELETE” API call is returning 202 (Accepted) while pass the arguments as query parameter rather than JSON body objects.
 
Please let us know your thoughts on this issue

**Comment by curb47** [comment]
@majidabdul The preferred approach would be to modify `JsonRequest.java` as you described above, passing the arguments as query parameters (if indeed the "DELETE" API call is accepting those parameters).  Modifying an underlying library would be a last resort solution.

**Comment by kristinpeterson** [comment]
@curb47 thanks & agreed!

@majidabdul can you please proceed w/ the preferred approach?

**Comment by majidabdul** [comment]
Thank you @curb47 and @kristinpeterson. Team has proceeded with the approach you suggested.

**Comment by attsdk** [comment]
Implemented in #22. Thank you @kristinpeterson, @curb47, @kk25q and @majidabdul.
